services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #Twig\Extensions\ArrayExtension: ~
    Twig\Extensions\DateExtension:
        arguments:
            - ~
    #Twig\Extensions\IntlExtension: ~
    Twig\Extensions\TextExtension: ~
